export const Images = {
    headerLogo: "/images/icon/IcLogo.png",
    banner: "/images/Illustration.png",
    Arrow: "/images/icon/IcArro.png",
    Arrow2: "/images/Arrow2.png",
    work1: "/images/work1.png",
    work2: "/images/work2.png",
    work3: "/images/work3.png",
    work4: "/images/work4.png",
    proArrow: "/images/proArrow.png",
    projectImg: "/images/project.png",
    Portfolio: "/images/Portfolio.png",
    Portfolio2: "/images/Portfolio2.png",
    user: "/images/user.png",
    tik: "/images/tik.png",
    pen: "/images/pen.png",
    que: "/images/que.png",
    timer: "/images/timer.png",
    note: "/images/note.png",
    AboutUs: "/images/AboutUs.png",
    leftArrow: "/images/leftArrow.png",
    rightArrow: "/images/rightArrow.png",
    Inquiry: "/images/Inquiry.png"
   };
  